Un poco de contenido, error fatal de compilación debido a  pubs.service.ts(21, 34) : error TS2339: Property 'id' does not exist on type 'QueryDocumentSnapshot<Pubs>'